ALTER TABLE "Coach" ADD COLUMN "headline" TEXT;
ALTER TABLE "Coach" ADD COLUMN "city" TEXT;
ALTER TABLE "Coach" ADD COLUMN "languages" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Coach" ADD COLUMN "settings" TEXT NOT NULL DEFAULT '{}';
